### ISSUE TITLE
Saving Landscapes to Prefabs

### ISSUE THREAD

**Issue by Kim-Eklund** [rionix/ShapesVisualizer#1]
When saving landscapes to prefabs, the landscape is invisible when placing the prefab.
I have no idea if it is possible to fix this or not, but understandable if it isn't.

**Comment by maltsevda** [comment]
Please describe the problem in more detail. Our component has nothing to do with the landscape. And there are no prefabs in the Unreal Engine.

**Comment by Kim-Eklund** [comment]
So sorry, I posted this on the entirely wrong plugin I just realized.
